### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by gamtiq** [nskazki/teleport-server#1]
There are several typos in README.md:
- Сообщать клиенту о **телепортируемых, их методах**, типах выбрасываемых событий
- Сообщать подключенным **клиентом** о выбрасываемых объектами событиях
- Работает только с асинхронными **методоми объктов**, принимающими неограниченное количество аргументов и callback.
- Все аргументы **передоваемые** на сервер и результаты возвращаемые на клиента проходят через JSON.stringify -> JSON.parse.
- если число - то это время ожидания в **миллесекундах**.
- имя поля (logBox, ipBox, blackBox) - **этоимя** под которым телепортируемых объект получат клиенты.

**Comment by nskazki** [comment]
спасибо :)
